export const EDGES = {
  grass: {
    up: ["grass", "grass1", "grass2", "water_river_br", "water_river_bl", "water_river_bc"],
    down: ["grass", "grass1", "grass2", "water_river_tl", "water_river_tr", "water_corner_tl", "water_corner_tr", "water_corner_tc", "water_river_rl"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["grass", "grass1", "grass2","water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  grass1: {
    up: ["grass", "grass1", "grass2", "water_river_br", "water_river_bl", "water_river_bc"],
    down: ["grass", "grass1", "grass2", "water_river_tl", "water_river_tr", "water_corner_tl", "water_corner_tr", "water_corner_tc", "water_river_rl"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["grass", "grass1", "grass2","water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  grass2: {
    up: ["grass", "grass1", "grass2", "water_river_br", "water_river_bl", "water_river_bc"],
    down: ["grass", "grass1", "grass2", "water_river_tl", "water_river_tr", "water_corner_tl", "water_corner_tr", "water_corner_tc", "water_river_rl"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["grass", "grass1", "grass2","water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  water: {
    up: ["water", "water_corner_tc", "water_river_entrance_u"],
    down: ["water", "water_corner_bc", "water_river_entrance_d"],
    left: ["water", "water_corner_cl", "water_dirtcorner_bl", "water_river_entrance_l", "water_dirtcorner_tl"],
    right: ["water", "water_corner_cr", "water_dirtcorner_br", "water_river_entrance_r", "water_dirtcorner_tr"],
  },
  water_corner_tl: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl"],
    down: ["water_corner_cl", "water_corner_bl"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["water_corner_tc", "water_corner_tr"],
  },
  water_corner_tc: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl"],
    down: ["water", "water_corner_bc", "water_river_entrance_d", "water_dirtcorner_br", "water_dirtcorner_bl"],
    left: ["water_corner_tl"],
    right: ["water_corner_tr"],
  },
  water_corner_tr: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl"],
    down: ["water_corner_cr", "water_corner_br"],
    left: ["water_corner_tc", "water_corner_tl"],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  water_corner_cl: {
    up: ["water_corner_cl", "water_corner_tl"],
    down: ["water_corner_cl", "water_corner_bl"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["water", "water_corner_cr", "water_river_entrance_r", "water_dirtcorner_tr", "water_dirtcorner_br"],
  },
  water_corner_cr: {
    up: ["water_corner_cr", "water_corner_tr"],
    down: ["water_corner_cr", "water_corner_br"],
    left: ["water", "water_corner_cl", "water_river_entrance_l", "water_dirtcorner_tl", "water_dirtcorner_bl"],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  water_corner_bl: {
    up: ["water_corner_cl", "water_corner_tl"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["water_corner_bc", "water_corner_br"],
  },
  water_corner_bc: {
    up: ["water", "water_corner_tc", "water_river_entrance_u", "water_dirtcorner_tr", "water_dirtcorner_tl"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl"],
    left: ["water_corner_bl"],
    right: ["water_corner_br"],
  },
  water_corner_br: {
    up: ["water_corner_cr", "water_corner_tr"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl"],
    left: ["water_corner_bc", "water_corner_bl"],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  water_river_tl: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl"],
    down: ["water_river_bl", "water_river_br", "water_river_d", "water_river_entrance_u"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["water_river_tr", "water_river_br", "water_river_rl", "water_river_entrance_l"],
  },
  water_river_tr: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl"],
    down: ["water_river_bl", "water_river_br", "water_river_d", "water_river_entrance_u"],
    left: ["water_river_tl", "water_river_bl", "water_river_rl", "water_river_entrance_r"],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  water_river_bl: {
    up: ["water_river_tl", "water_river_tr", "water_river_d", "water_river_entrance_d"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["water_river_tr", "water_river_br", "water_river_rl", "water_river_entrance_l"],
  },
  water_river_br: {
    up: ["water_river_tl", "water_river_tr", "water_river_d", "water_river_entrance_d"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl"],
    left: ["water_river_tl", "water_river_bl", "water_river_rl", "water_river_entrance_r"],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  water_river_entrance_d: {
    up: ["water", "water_corner_tc", "water_river_entrance_u", "water_dirtcorner_tr", "water_dirtcorner_tl"],
    down: ["water_river_bl", "water_river_br", "water_river_d", "water_river_entrance_u"],
    left: ["water_dirtcorner_br"],
    right: ["water_dirtcorner_bl"],
  },
  water_river_entrance_u: {
    up: ["water_river_tl", "water_river_tr", "water_river_d", "water_river_entrance_d"],
    down: ["water", "water_corner_bc", "water_river_entrance_d", "water_dirtcorner_br", "water_dirtcorner_bl"],
    left: ["water_dirtcorner_tr"],
    right: ["water_dirtcorner_tl"],
  },
  water_river_d: {
    up: ["water_river_tl", "water_river_tr", "water_river_d", "water_river_entrance_d"],
    down: ["water_river_bl", "water_river_br", "water_river_d", "water_river_entrance_u"],
    left: ["grass", "grass1", "grass2", "water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr", "water_river_br", "water_river_d"],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_bl", "water_river_d"],
  },
  water_river_rl: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl"],
    left: ["water_river_tl", "water_river_bl", "water_river_entrance_r"],
    right: ["water_river_tr", "water_river_br", "water_river_entrance_l"],
  },
  water_river_entrance_r: {
    up: ["water_dirtcorner_br"],
    down: ["water_dirtcorner_tr"],
    left: ["water", "water_corner_cl", "water_river_entrance_l", "water_dirtcorner_tl", "water_dirtcorner_bl"],
    right: ["water_river_entrance_l", "water_river_rl", "water_river_tr", "water_river_br"],
  },
  water_river_entrance_l: {
    up: ["water_dirtcorner_bl"],
    down: ["water_dirtcorner_tl"],
    left: ["water_river_entrance_r", "water_river_rl", "water_river_tl", "water_river_bl"],
    right: ["water", "water_corner_cr", "water_river_entrance_r", "water_dirtcorner_tr", "water_dirtcorner_br"],
  },
  water_dirtcorner_tl: {
    up: ["water_dirtcorner_bl", "water_river_entrance_l"],
    down: ["water", "water_corner_bc", "water_river_entrance_d", "water_dirtcorner_br", "water_dirtcorner_bl"],
    left: ["water_dirtcorner_tr"],
    right: ["water", "water_corner_cr", "water_river_entrance_r", "water_dirtcorner_tr", "water_dirtcorner_br"],
  },
  water_dirtcorner_tr: {
    up: ["water_dirtcorner_br", "water_river_entrance_r"],
    down: ["water", "water_corner_bc", "water_river_entrance_d", "water_dirtcorner_br", "water_dirtcorner_bl"],
    left: ["water", "water_corner_cl", "water_river_entrance_l", "water_dirtcorner_tl", "water_dirtcorner_bl"],
    right: ["water_dirtcorner_tl"],
  },
  water_dirtcorner_bl: {
    up: ["water", "water_corner_tc", "water_river_entrance_u", "water_dirtcorner_tr", "water_dirtcorner_tl"],
    down: ["water_dirtcorner_tl", "water_river_entrance_l"],
    left: ["water_dirtcorner_br"],
    right: ["water", "water_corner_cr", "water_river_entrance_r", "water_dirtcorner_tr", "water_dirtcorner_br"],
  },
  water_dirtcorner_br: {
    up: ["water", "water_corner_tc", "water_river_entrance_u", "water_dirtcorner_tr", "water_dirtcorner_tl"],
    down: ["water_dirtcorner_tr", "water_river_entrance_r"],
    left: ["water", "water_corner_cl", "water_river_entrance_l", "water_dirtcorner_tl", "water_dirtcorner_bl"],
    right: ["water_dirtcorner_bl"],
  },
  water_river_ending_u: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl"],
    down: ["water_river_d", "water_river_entrance_u"],
    left: ["grass", "grass1", "grass2","water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr",  "water_river_ending_r", "water_river_br", "water_river_d"],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_ending_l", "water_river_bl", "water_river_d"],
  },
  water_river_ending_d: {
    up: ["water_river_d", "water_river_entrance_d", "water_river_tr", "water_river_tl"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl"],
    left: ["grass", "grass1", "grass2","water_corner_tr", "water_corner_cr", "water_corner_br", "water_river_tr",  "water_river_ending_r", "water_river_br", "water_river_d"],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_ending_l", "water_river_bl", "water_river_d"],
  },
  water_river_ending_r: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl", "water_river_ending_d"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl", "water_river_ending_u"],
    left: ["water_river_rl", "water_river_tr", "water_river_bl","water_river_tl", "water_river_ending_l", ],
    right: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_ending_l", "water_river_bl", "water_river_d", "water_river_ending_d", "water_river_ending_u"],
  },
  water_river_ending_l: {
    up: ["grass", "grass1", "grass2", "water_corner_bl", "water_corner_bc", "water_corner_br", "water_river_bl", "water_river_br", "water_river_rl", "water_river_ending_d"],
    down: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_tc", "water_corner_tr", "water_river_tl", "water_river_tr", "water_river_rl", "water_river_ending_u"],
    right: ["water_river_rl", "water_river_tr", "water_river_bl","water_river_tl", "water_river_ending_l", ],
    left: ["grass", "grass1", "grass2", "water_corner_tl", "water_corner_cl", "water_corner_bl", "water_river_tl", "water_river_ending_l", "water_river_bl", "water_river_d", "water_river_ending_d", "water_river_ending_u"],
  },
};
