import UnitBase from "./UnitBase.js";
import { registerUnitType } from "../units.js";

// Example unit showing defaults for a derived type.
export default class ExampleSoldier extends UnitBase {
  constructor(opts = {}) {
    super({
      ...opts,
      faction: opts.faction || "friendly",
      sprite: opts.sprite || { sx: 16, sy: 5 },
      hp: opts.hp ?? 18,
      atk: opts.atk ?? 4,
      move: opts.move ?? 5,
      range: opts.range ?? 1,
      images: opts.images || [
        "/GameLogos/logo1.png",
        "/GameLogos/logo2.png",
        "/GameLogos/logo2.png",
      ],
      info: opts.info || {
        headline: "Headline",
        text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur malesuada ornare bibendum. Nulla luctus erat porta enim eleifend, sed scelerisque dui lacinia. Nulla vitae dolor augue. Nullam accumsan, neque fringilla semper rutrum, risus nisi suscipit orci, eu ultricies lacus purus nec ex. Nam et diam lacinia, lobortis justo a, eleifend massa. Nunc ornare nisi nibh, et mollis magna pretium eu. Sed tincidunt arcu posuere dui pulvinar porta. Donec imperdiet tempus velit, in tempus quam sagittis ac. Praesent vehicula nisi sit amet nunc condimentum, sit amet placerat lacus elementum. Proin id magna vel arcu porttitor sollicitudin vel at tellus. Morbi eget pharetra nulla. Sed nec mauris quis tellus auctor ullamcorper quis at diam. Donec et sagittis mi.\n
Nullam aliquet pharetra placerat. Sed eu luctus dui, sed laoreet justo. Fusce sed turpis porttitor ex ullamcorper semper. Pellentesque eu molestie eros, id ornare augue. Vivamus eget semper ex. Quisque elit mauris, convallis et laoreet ac, eleifend non quam. Aenean auctor a mi sit amet ultricies. Nulla facilisi. Nullam aliquam, libero ac vestibulum efficitur, lectus augue feugiat sem, eget tempor augue mi id mauris. Sed sapien nisi, vulputate eu aliquet nec, ornare et massa. Nulla maximus, nisl vel molestie tempus, massa nulla gravida mauris, vel consequat felis orci eget nulla. Mauris ut ante sodales, rhoncus justo eget, molestie eros.\n
Aliquam erat volutpat. Nunc urna nibh, lobortis in ornare aliquet, ultrices ut sem. Suspendisse sollicitudin ligula lectus, a tincidunt purus tempor ac. Etiam quis fringilla felis. Pellentesque feugiat cursus lorem, et porttitor nisl placerat sed. Fusce eget mauris tincidunt, condimentum purus id, semper nulla. Vestibulum in erat ante. Quisque sed sollicitudin mi, ullamcorper pellentesque ipsum. Duis sagittis placerat enim id mattis. Suspendisse vitae sollicitudin sem, vel aliquet est. Integer nec nibh gravida, dapibus justo vitae, consequat diam. Phasellus ut enim tincidunt, pretium velit ac, auctor felis. Nulla fringilla, sapien a porttitor fringilla, neque ex ultrices ex, vel viverra lectus leo non sapien. Vivamus id est maximus, mollis nisi in, feugiat enim. Fusce vel congue mi. Pellentesque cursus nisl dictum nisi fermentum, sed ornare nulla fermentum.

Duis euismod sed leo eu efficitur. Etiam id mi a nibh tempus lacinia. Morbi sollicitudin aliquet dolor, vel molestie leo dictum ut. Pellentesque ut rutrum enim. Nam ut luctus nisl. Sed tempus neque at nulla vestibulum, sit amet iaculis ex suscipit. Nunc vehicula augue ut pharetra pretium. Mauris luctus, ligula non pellentesque luctus, libero dolor posuere eros, eget egestas quam augue id nisi. In blandit orci iaculis ligula interdum viverra eget sed nunc. Aliquam pulvinar mi nec ex malesuada, in elementum arcu cursus. Mauris ornare tellus in magna congue, et efficitur ipsum molestie. Quisque velit enim, iaculis a viverra vel, pulvinar sit amet sapien. Morbi commodo cursus mi vel consequat. Integer semper tristique lectus et aliquet.

Donec ac nisl a sem ultrices varius. Quisque ac nisi eros. Phasellus maximus dui at sem fermentum, ut auctor risus auctor. Nunc volutpat est at nunc bibendum scelerisque. Maecenas sed risus eget nisi pellentesque maximus ac eget ipsum. Morbi vel mollis velit. Ut eget feugiat magna, eget hendrerit mi. Suspendisse volutpat pretium interdum. Aenean tincidunt eleifend malesuada. Donec et dui a nisl varius convallis. Sed quam libero, auctor ut faucibus ac, cursus tincidunt ligula. Pellentesque interdum sem lacinia risus maximus, eu ornare nisl vestibulum. Aliquam non nibh augue. Praesent ut malesuada nisl, tempor luctus orci.

Sed vestibulum dignissim ante, nec varius elit fermentum nec. Vivamus auctor tellus a tempor laoreet. Maecenas sagittis, urna vestibulum sagittis euismod, nisi urna interdum lorem, id aliquam mi ex gravida nibh. Vivamus eleifend at elit a elementum. Integer lacus tortor, cursus a dictum vitae, luctus et odio. Aenean rutrum rhoncus augue. Suspendisse semper at tortor tincidunt rutrum. Cras sed pellentesque purus, at maximus turpis. Donec tempus, risus id malesuada iaculis, neque nibh porta libero, ut tempus mauris justo vitae orci. Mauris id leo ac metus maximus posuere sed eget purus. Vivamus porttitor iaculis ultricies. Nam iaculis congue lacus et aliquam. Ut urna orci, varius ut enim a, gravida rutrum augue. Maecenas a tempus enim, vitae placerat dolor. Sed at pharetra est, accumsan auctor justo.

Pellentesque euismod rhoncus rhoncus. Quisque sodales tellus urna, vitae tempus mauris accumsan et. Nulla augue ex, vehicula eget sapien sit amet, vestibulum iaculis lorem. Suspendisse auctor a tortor at euismod. Suspendisse bibendum pharetra libero, venenatis finibus erat bibendum a. Praesent a tempor dui, vel fringilla libero. Vivamus lobortis tincidunt urna at scelerisque. Morbi sed felis velit. Nulla vel eros ultricies, gravida ipsum et, aliquam enim. Vivamus tempor leo urna, ac ornare turpis eleifend vel.

Etiam justo erat, cursus a eros vitae, finibus efficitur arcu. Aliquam erat volutpat. Quisque blandit massa vel posuere tincidunt. Donec scelerisque, erat non suscipit ultrices, eros enim tristique massa, ac efficitur tortor lacus vel nisi. Sed eget venenatis ex, sed accumsan magna. Vestibulum ultricies blandit nisl a facilisis. Quisque convallis vulputate cursus. Pellentesque non nisl eget lorem maximus dapibus. Nunc elit tortor, fermentum non consectetur non, tincidunt non turpis. Morbi nibh massa, tincidunt sit amet felis id, efficitur tincidunt justo. Nam vel lectus porttitor, consectetur ligula eu, ullamcorper magna. Nullam porttitor ac quam vitae ullamcorper. Proin nunc neque, fringilla eu tortor quis, ultricies sodales ligula. Nulla ligula turpis, luctus in scelerisque non, lacinia vitae elit. Duis augue mauris, mattis at odio at, fermentum ultricies velit.

Cras eu nulla eros. Fusce pretium neque non sapien sollicitudin eleifend. In at porta lorem. In porta tortor augue, nec lacinia nisl interdum ut. Donec sed accumsan nulla. Vivamus lacus nibh, volutpat at malesuada eget, consequat in nisl. Integer blandit, ex ut facilisis vulputate, ipsum tellus luctus urna, ac tincidunt metus urna quis erat. Cras euismod, libero convallis venenatis aliquet, augue ante vulputate turpis, id tempor ipsum velit eget odio. Donec lorem mauris, pulvinar nec fermentum sed, gravida non nisl. Mauris at nisl id turpis lobortis vestibulum. Maecenas vestibulum lectus enim, et accumsan purus pharetra nec. Aenean maximus semper mauris, at ultrices dui lobortis et.

Nulla tristique dui eros, vitae ullamcorper ante blandit sed. Aenean tempor ullamcorper pellentesque. Nam aliquam, orci eget vestibulum consectetur, tortor dolor mollis magna, ac vestibulum nibh dolor vel leo. Quisque imperdiet lacus sit amet vestibulum porta. Aenean ut augue id felis lacinia iaculis at quis risus. Curabitur congue tortor nec sodales fermentum. Nullam nunc orci, semper quis urna et, venenatis sodales turpis. Sed iaculis mi nec fringilla vehicula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sit amet quam ac est vestibulum vehicula. Vestibulum vehicula lectus tortor, rutrum mattis lacus aliquet sit amet. Nulla dictum, nisi in pulvinar convallis, ante dui scelerisque diam, nec porta mi risus vitae tortor. Mauris in accumsan nibh, sed vulputate est. Nullam tincidunt odio ex, non pretium neque lobortis et. Phasellus eleifend mattis volutpat.

Nullam auctor nibh quis euismod dignissim. Duis non magna venenatis, commodo mauris vel, congue odio. In ut ullamcorper ipsum. Aenean accumsan libero nec elit finibus tincidunt. Nulla varius, orci ut finibus lacinia, lacus orci varius tellus, sit amet pulvinar leo eros at est. In nec velit sed nisl commodo varius. Donec sollicitudin nisl purus, sit amet varius lectus placerat ac. Nunc scelerisque ultrices libero, a ullamcorper nibh suscipit vitae. Donec fermentum augue ullamcorper, iaculis dolor sit amet, dignissim ante. Sed accumsan mattis mi, non iaculis sapien suscipit a. Etiam imperdiet felis id tempor aliquet. Ut ligula dui, auctor at augue fringilla, blandit viverra felis. Maecenas a lectus pharetra, consectetur augue eget, feugiat odio. Phasellus eu rhoncus nisl.

Nam sit amet ligula ultricies, commodo sem faucibus, scelerisque massa. Pellentesque eget ante sed mauris finibus molestie vitae sit amet neque. Curabitur aliquam rhoncus mi, ullamcorper luctus mauris vehicula eget. Duis nec tortor nec metus pretium placerat ac ut erat. Donec non dolor elementum, porttitor quam et, elementum nulla. Sed diam nunc, pharetra quis arcu ut, feugiat ullamcorper arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque interdum et justo quis convallis. Etiam nec fringilla nunc. Vestibulum sed dictum nisi. Etiam blandit ullamcorper odio, eu imperdiet erat condimentum eu. Aenean lobortis suscipit orci ac fermentum.

Curabitur pellentesque orci ultricies quam efficitur tempus. Quisque eu pharetra libero. Praesent volutpat maximus nibh, vel auctor purus efficitur ac. Maecenas lacinia porta urna, posuere hendrerit ipsum varius a. Sed magna nunc, lobortis sit amet odio ac, ornare rutrum ante. Pellentesque mauris urna, molestie quis aliquam ut, tincidunt in mauris. Vivamus massa ex, mollis id posuere in, bibendum ac tellus. Vivamus quis lacinia nisl. In sed blandit est, vehicula ultricies elit. Phasellus dignissim consectetur maximus. Phasellus gravida nisl quis dolor luctus iaculis.

Phasellus luctus metus eget pulvinar consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi feugiat orci in facilisis fermentum. Sed purus leo, congue at luctus at, viverra feugiat elit. Ut eget accumsan erat. Cras arcu risus, tempor vehicula dapibus sed, mattis a erat. Duis ornare lorem eu risus auctor tempor. Donec mattis enim odio, cursus bibendum nisi consequat eget. In sodales urna at felis commodo fringilla. Maecenas eget cursus massa. Proin nec orci velit. Nam molestie turpis ut posuere mattis. Sed vel mauris sit amet orci pretium rutrum ut vel tortor.

Nullam aliquam dictum turpis tincidunt gravida. Ut ornare congue leo eu mollis. Fusce iaculis ligula sit amet orci facilisis rhoncus nec nec urna. Sed ac libero ac quam posuere accumsan. Nullam at urna quis ipsum tempus pulvinar at ac massa. Etiam aliquam risus a aliquet congue. Proin eu consectetur nunc. Maecenas scelerisque, dolor quis malesuada lobortis, ex tellus iaculis elit, et euismod nunc est quis risus. Ut auctor enim at leo lacinia, eget efficitur arcu accumsan. Ut varius purus ut condimentum pharetra. Mauris vel convallis sem. Aenean vitae est consequat erat fringilla aliquam. Nunc ante nulla, luctus at sagittis at, elementum lacinia nibh.

Ut in velit laoreet sem pretium sodales ac at metus. Etiam vehicula diam quam, non vestibulum diam tincidunt nec. Integer eu justo ac nisi rhoncus dapibus eu nec enim. Integer iaculis posuere pretium. Aenean viverra neque ac massa imperdiet sagittis. Donec volutpat metus a ullamcorper ultricies. Mauris interdum nisl sit amet ex ullamcorper, eget maximus ante ornare. Ut eget elit mi. Nulla nibh sapien, eleifend at porttitor at, venenatis eu mi. Etiam ullamcorper, mi vitae tincidunt rhoncus, est ex iaculis risus, et imperdiet tellus orci vitae ante. Suspendisse vel ipsum venenatis, mattis nunc interdum, ultricies ante. Fusce vitae ultricies ipsum, eu gravida turpis.

Nullam vehicula sagittis viverra. In vitae suscipit eros. Integer vitae nisl aliquam, placerat neque nec, scelerisque arcu. Cras ultrices nunc et pulvinar finibus. Sed vestibulum massa felis, non scelerisque eros dictum ac. Nunc porta malesuada elit non laoreet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque tempor euismod purus nec cursus. Maecenas fringilla sollicitudin commodo. Sed a leo vel sem facilisis volutpat. Sed et viverra augue. In hac habitasse platea dictumst. Nullam mattis felis in tortor auctor tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam vitae velit ultrices, convallis dui ac, condimentum ligula.

Pellentesque libero erat, dictum nec tellus ac, feugiat lobortis sapien. Phasellus metus augue, blandit et rutrum at, volutpat at est. Sed faucibus nisl eu erat pretium, in facilisis magna placerat. Nunc aliquet, ipsum eu vehicula laoreet, magna arcu mattis felis, sed dictum diam ipsum nec nunc. Donec pharetra eros id mauris vehicula commodo. Nunc convallis eros sed mattis sollicitudin. Aenean eleifend dignissim sagittis. Proin odio ex, consectetur aliquam lacus sed, rutrum porttitor augue. Sed ultrices est arcu, nec viverra sem iaculis ac. In sit amet ex a lectus malesuada pulvinar.

Vivamus congue ante non tincidunt tristique. Nullam scelerisque tortor nunc, sed gravida augue pulvinar quis. Vestibulum porttitor elit vel odio egestas interdum. Donec tristique quam sed aliquet porttitor. Maecenas pulvinar eleifend nisl tincidunt mollis. Maecenas hendrerit lectus massa, id tempus libero consectetur ac. Proin semper fermentum eros, at volutpat nibh dapibus id. Mauris efficitur ipsum a est volutpat porttitor. Nulla metus turpis, elementum ultricies nibh a, ultrices viverra lorem. Maecenas neque ante, placerat vitae tortor at, elementum tincidunt turpis. Vestibulum ut neque sit amet massa pretium bibendum. Sed suscipit, lorem vitae malesuada ornare, enim ex efficitur sapien, at ultrices mi nunc et ligula.

Maecenas tempus in ligula sit amet dignissim. Ut commodo egestas erat eget gravida. In eget sem elementum, dictum nunc eu, elementum nunc. In vestibulum tempus nisi. Suspendisse tincidunt a neque ut maximus. Vivamus hendrerit ante quis laoreet maximus. Maecenas commodo urna eu mauris dictum tempor. Proin non auctor tellus, et auctor augue. `
      }
    });
  }
}

// register this example so it can be created by type name
registerUnitType("ExampleSoldier", ExampleSoldier);
